[project]
name = "webscrape8minstreamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "firecrawl-py>=4.13.0",
    "openai>=2.15.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.53.0",
]
